name: publish

on:
    release:
        types: [released]

jobs:
    publish:
        name: Release build and publish
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v2

            - name: Set up JDK 11
              uses: actions/setup-java@v1
              with:
                  java-version: 11

            - name: Create binary keyring
              env:
                  GPG_KEY_CONTENTS: ${{ secrets.SIGNING_KEY_SECRET }}
                  SIGNING_KEY_RING_FILE: ${{ secrets.SIGNING_KEY_FILE_PATH }}
              run: |
                  git fetch --unshallow
                  sudo bash -c "echo '$GPG_KEY_CONTENTS' | base64 -d > '$SIGNING_KEY_RING_FILE'"

            - name: Publish to MavenCentral
              run: ./gradlew --max-workers 1 --no-daemon publishReleasePublicationToSonatypeRepository closeAndReleaseRepository
              env:
                  SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
                  SIGNING_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
                  SIGNING_KEY_FILE_PATH: ${{ secrets.SIGNING_KEY_FILE_PATH }}
                  OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
                  OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
                  SONATYPE_PROFILE_ID: ${{ secrets.SONATYPE_PROFILE_ID }}
