name: publish

on:
    workflow_dispatch:
    release:
        types: [released]

jobs:
    publish:
        name: Release build and publish
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v2

            - name: Set up JDK 17
              uses: actions/setup-java@v1
              with:
                distribution: 'zulu'
                java-version: 17

            # Setup aar signing
            - name: Create binary keyring
              env:
                  GPG_KEY_CONTENTS: ${{ secrets.SONATYPE_BASE64_SIGNING_KEY }}
                  SIGNING_KEY_RING_FILE: "${TMPDIR}key.gpg"
              run: |
                  git fetch --unshallow
                  sudo bash -c "echo '$GPG_KEY_CONTENTS' | base64 -d > '$SIGNING_KEY_RING_FILE'"

            # Build and run all tests. This ensures all artifacts are built.
            - name: Build & Test
              run: ./gradlew build

            # Publish aar to maven central via sonatype repository
            - name: Publish to MavenCentral
              run: ./gradlew -PmavenCentralUsername=${{ secrets.OSSRH_USERNAME }} -PmavenCentralPassword="${{ secrets.OSSRH_PASSWORD }}" -Psigning.keyId=${{ secrets.SONATYPE_SIGNING_KEY_ID }} -Psigning.password="${{ secrets.SONATYPE_SIGNING_KEY_PASSWORD }}" -Psigning.secretKeyRingFile=$SIGNING_KEY_RING_FILE --no-parallel --no-daemon publishAndroidReleasePublicationToMavenCentralRepository closeAndReleaseRepository
            - name: Publish to MavenCentral
              run: ./gradlew -PmavenCentralUsername=${{ secrets.OSSRH_USERNAME }} -PmavenCentralPassword="${{ secrets.OSSRH_PASSWORD }}" -Psigning.keyId=${{ secrets.SIGNING_KEY_ID }} -Psigning.password="${{ secrets.SIGNING_KEY_PASSWORD }}" -Psigning.secretKeyRingFile=${{ secrets.SIGNING_KEY_FILE_PATH }} --no-parallel --no-daemon publishAllPublicationsToMavenCentralRepository closeAndReleaseRepository
