name: publish

on:
    workflow_dispatch:
    release:
        types: [released]

env:
    SIGNING_KEY_RING_FILE: "${RUNNER_TEMP}key.gpg"

jobs:
    publish:
        name: Release build and publish
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v2

            - name: Set up JDK 17
              uses: actions/setup-java@v1
              with:
                distribution: 'zulu'
                java-version: 17

            # Setup aar signing
            - name: Create binary keyring
              env:
                  GPG_KEY_CONTENTS: ${{ secrets.SONATYPE_BASE64_SIGNING_KEY }}
              run: |
                  git fetch --unshallow
                  sudo bash -c "echo '$GPG_KEY_CONTENTS' | base64 -d > '$SIGNING_KEY_RING_FILE'"

            # Publish aar to maven central via sonatype repository
            - name: Publish to MavenCentral
              run: ./gradlew -PmavenCentralUsername=${{ secrets.OSSRH_USERNAME }} -PmavenCentralPassword="${{ secrets.OSSRH_PASSWORD }}" -Psigning.keyId=${{ secrets.SONATYPE_SIGNING_KEY_ID }} -Psigning.password="${{ secrets.SONATYPE_SIGNING_KEY_PASSWORD }}" -Psigning.secretKeyRingFile="$SIGNING_KEY_RING_FILE" --no-parallel --no-daemon publishAllPublicationsToMavenCentralRepository closeAndReleaseRepository
