name: publish

on:
    workflow_dispatch:
    release:
        types: [released]

env:
    SIGNING_KEY_RING_FILE: "${RUNNER_TEMP}key.gpg"

jobs:
    publish:
        name: Release build and publish
        runs-on: ubuntu-latest
        steps:
            # Check out current repository
            - name: Fetch Sources
              uses: actions/checkout@v2.3.4
              with:
                ref: ${{ github.event.release.tag_name }}

            - name: Set up JDK 17
              uses: actions/setup-java@v1
              with:
                java-version: 17

            # Update Unreleased section with the current release note
            - name: Patch Changelog
              run: |
                  ./gradlew patchChangelog --release-note="`cat << EOM
                  ${{ github.event.release.body }}
                  EOM`"

            # Setup aar signing
            - name: Create binary keyring
              env:
                  GPG_KEY_CONTENTS: ${{ secrets.SONATYPE_BASE64_SIGNING_KEY }}
              run: |
                  git fetch --unshallow
                  sudo bash -c "echo '$GPG_KEY_CONTENTS' | base64 -d > '$SIGNING_KEY_RING_FILE'"

            # Publish aar to maven central via sonatype repository
            - name: Publish to MavenCentral
              run: ./gradlew -PmavenCentralUsername=${{ secrets.OSSRH_USERNAME }} -PmavenCentralPassword="${{ secrets.OSSRH_PASSWORD }}" -Psigning.keyId=${{ secrets.SONATYPE_SIGNING_KEY_ID }} -Psigning.password="${{ secrets.SONATYPE_SIGNING_KEY_PASSWORD }}" -Psigning.secretKeyRingFile="$SIGNING_KEY_RING_FILE" --no-parallel --no-daemon publishAllPublicationsToMavenCentralRepository closeAndReleaseRepository

            # Create pull request
            - name: Create Pull Request
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  VERSION="${{ github.event.release.tag_name }}"
                  BRANCH="changelog-update-$VERSION"
                  git config user.email "action@github.com"
                  git config user.name "GitHub Action"
                  git checkout -b $BRANCH
                  git commit -am "Changelog update - $VERSION"
                  git push --set-upstream origin $BRANCH
                  gh pr create \
                    --title "Changelog update - \`$VERSION\`" \
                    --body "Current pull request contains patched \`changelog.md\` file for the \`$VERSION\` version." \
                    --base master \
                    --head $BRANCH
